version: "3.9"

services:
  backend:
    image: abhishek8056/flask-backend:v3
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  frontend:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8090:80"
    depends_on:
      - backend

