version: "3.8"
services:
  backend:
    image: flask-backend:latest
    build: .
    container_name: flask-backend
    ports:
      - "5001:5000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  frontend:
    image: nginx:alpine
    container_name: nginx-frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    deploy:
      replicas: 1
    depends_on:
      - backend
